# Generated by Django 6.0.5 on 2026-05-31 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('Internal', 'Internal'), ('Assignment', 'Assignment'), ('Midterm', 'Midterm'), ('Final', 'Final')], max_length=50)),
                ('marks', models.IntegerField()),
                ('max_marks', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_records', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'ordering': ['-exam_date'],
            },
        ),
    ]
